### PR TITLE
Add Docker configuration

### PR DESCRIPTION
**Pull request by dajvido**
I've been wondering if put any notes into the README or not after all. It's very basic Docker, so running it up is as easy as `docker-compose up` 🤔

### CODE REVIEW

**Comment by Maks-s** [comment]
Hi 😺 
Thanks for the contribution !
However, I don't really understand why would you want to add Docker, could you explain the benefits please ?

**Comment by dajvido** [comment]
Hi @Maks-s 
I personally keep as few dependencies for building apps on my machine as possible. I do prefer to keep everything in an isolated environment using Docker. I made it originally for my personal use in mind, but as I love open-source I wanted to share it if anyone else would like to run it without having node installed 🙂

**Comment by Maks-s** [comment]
Looks like a good idea then. @daed, what do you think ?

Also, yes, I think adding a little note in the README would be more efficient instead of checking if Docker configuration files exists

**Comment by daed** [comment]
Yeah, I have no problem with this.  I don't think I fully understand the benefit, but it seems benign enough that if it's a feature people could use, there's no reason not to include it.

@dajvido would you mind putting together a quick addition to the readme?   A brief background on use case and any extra instructions would be fantastic!

**Comment by dajvido** [comment]
Sure, I will add some details to README tomorrow

**Pull request merged**
